# Example of bipartite networks using the data generated by
# Krageberger et al. 2018, Mastrevirus in Africa. 
# --------------------------------------------------------------------------------------
# Libraries required biparrite and igraph
# If not installed type  install.packages("bipartite") and install.packages("igraph")
library(bipartite)
library(igraph)
# -----------------------------
setwd('PATH_TO_DIRECTORY')
# Loading the data from Krageberger, table A figure 1.
mastre <- read.csv("data/Mastre_Kraberger_2018.csv", row.names = 1, as.is=T)
# mastre = t(mastre) #Transpossing the data
mastre
#--------------------------------------------------------------------------------------
# Bipartite analysis
plotweb(sortweb(mastre, sort.order="inc"), method="normal")   
visweb(sortweb(mastre,sort.order="inc"), type="nested", labsize=2,
       square="interaction", text="none", textsize = 3,circles=FALSE, frame=FALSE)


mastre.sp.table  <- specieslevel(mastre)
mastre.sp.table
mastre.net.table <- networklevel(mastre, weighted=TRUE, )
mastre.net.table
mastre.nest.table <- nestedcontribution(mastre)

mastre.mod.table <- computeModules(mastre, method="DormannStrauss") 

#
degreedistr(mastre)

#--------------------------------------------------------------------------------------
# Bipartite network: package iGraph
# Generating graph object from the Mastrevirus association matrix from Kragerberger et al. 2018
Mastre.g=graph.incidence(mastre, weighted=T)

# Getting cols and rows names
rownames(mastre)
colnames(mastre)

# Adding attributes to graph
# Vertex names and attributes
V(Mastre.g)$type
V(Mastre.g)$name
V(Mastre.g)$color <- c("#493820","#816C5B","#A9A18C","#613318","#855723","#B99C6B","#8F3B1B",
                       "#D57500","#DBCA69","#404F24","#668D3C","#BDD09F","#4E6172","#83929F",
                       "#A3ADB8", "#B2182B", "#D6604D", "#F4A582", "#FDDBC7", "#D1E5F0", "#92C5DE",
                       "#4393C3", "#2166AC", "#CCC000", "#493834", "#816C7B", rep("orange", 36)) 
                       # c("red", "deeppink4", "gray", "purple", rep("orange", 11), rep("darkgreen", 9), "blue", "darkgoldenrod", "olivedrab4",
            		   # rep("blue", 2), rep("lightblue", 3), rep("burlywood4", 3), "brown", rep("wheat3", 28))
show_col(unique(V(Mastre.g)$color))

shapes = c(rep("square", length(V(Mastre.g)$type[V(Mastre.g)$type == "FALSE"])), rep("circle", length(V(Mastre.g)$type[V(Mastre.g)$type == "TRUE"])))

# shapes <-  c(rep("circle", 36), rep("square", 28))
V(Mastre.g)$xx <- log(V(Mastre.g)) # coverage size

# Edges names and attributes
E(Mastre.g)$width <- log(E(Mastre.g)$weight)+1
rbPal <- colorRampPalette(c("orange", "red2")) 
E(Mastre.g)$color <- rbPal(10)[as.numeric(cut(E(Mastre.g)$width, breaks = 10))]

# Adding legends if needed
# legend <- unique(cbind(colorName=V(Pap)$color,Region=as.character(cnodes)))

# As ______________ layout
plot(Mastre.g, edge.arrow.size=1, vertex.shape=shapes, vertex.size=10, vertex.label.cex=0.6, vertex.label.color='black', vertex.frame.color="gray", 
     vertex.frame.color="gold",   edge.curved=F,  layout=layout_with_mds(Mastre.g)) # maxiter=100)) #, fineiter = 100, cool.fact=0.80, weight.edge.crossings = 0.5 - sqrt(edge_density(Mastre.g))))
# As bipartite layout
plot(Mastre.g, edge.arrow.size=1, vertex.shape=shapes, vertex.size=10, vertex.label.cex=0.6, vertex.label.color='black', vertex.frame.color="gray", 
     vertex.frame.color="gold", edge.curved=F, layout=layout_as_bipartite(Mastre.g, types=NULL, hgap=1, vgap=1, maxiter=100))



